apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-values
  namespace: cert-manager
data:
  values.yaml: |
    global:
      leaderElection:
        namespace: cert-manager # default is "kube-system" which seems to prevent status checks from working
    nodeSelector:
      gke.kfirs.com/purpose: workloads
    tolerations:
      - effect: NoExecute
        key: gke.kfirs.com/purpose
        operator: Equal
        value: workloads
    installCRDs: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: cert-manager@arikkfir-primary.iam.gserviceaccount.com
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arikkfir-primary.iam.gserviceaccount.com
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
    cainjector:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 150Mi
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arikkfir-primary.iam.gserviceaccount.com
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
    startupapicheck:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 50Mi
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arikkfir-primary.iam.gserviceaccount.com
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
